apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "drone.fullname" . }}-server
  labels:
    app: {{ template "drone.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DRONE_DEBUG: 'false'
  DRONE_DATABASE_DRIVER: sqlite3
  DRONE_DATABASE_DATASOURCE: /var/lib/drone/drone.sqlite
  DRONE_PROVIDER: {{ .Values.config.provider }}
  DRONE_OPEN: {{ .Values.config.open | quote }}
  DRONE_ADMIN: {{ .Values.config.username }}
  {{- if (eq .Values.config.provider "github") }}
  DRONE_GITHUB: 'true'
  DRONE_GITHUB_CLIENT: {{ .Values.config.client }}
  DRONE_GITHUB_CONTEXT: continuous-integration/drone
  DRONE_GITHUB_GIT_USERNAME: {{ .Values.config.username }}
  DRONE_GITHUB_MERGE_REF: 'true'
  DRONE_GITHUB_PRIVATE_MODE: 'false'
  DRONE_GITHUB_SCOPE: repo,repo:status,user:email,read:org
  DRONE_GITHUB_SKIP_VERIFY: 'true'
  {{- else if (eq .Values.config.provider "gitlab") }}
  DRONE_GITLAB: 'true'
  DRONE_GITLAB_CLIENT: {{ .Values.config.client }}
  DRONE_GITLAB_URL: {{ .Values.config.providerUrl }}
  {{- else if (eq .Values.config.provider "gitea") }}
  DRONE_GITEA: 'true'
  DRONE_GITEA_URL: {{ .Values.config.providerUrl }}
  {{- else if (eq .Values.config.provider "gogs") }}
  DRONE_GOGS: 'true'
  DRONE_GOGS_URL: {{ .Values.config.providerUrl }}
  {{- else if (eq .Values.config.provider "bitbucket-cloud") }}
  DRONE_BITBUCKET: 'true'
  DRONE_BITBUCKET_CLIENT: {{ .Values.config.client }}
  {{- end }}
