{{- if .Values.ingress.enabled }}
{{- $fullName := include "drone.fullname" . }}
{{- $httpPort := .Values.service.httpPort }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "drone.name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "drone.fullname" . }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- if index $.Values.ingress "annotations" }}
          {{- if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" }}
          - path: /*
          {{- else }}{{/* Has annotations but ingress class is not "gce" */}}
          - path: /
          {{- end }}
        {{- else }}{{/* Has no annotations */}}
          - path: /
        {{- end }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $httpPort }}
  {{- end }}
  {{- if .Values.ingress.ssl }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - name: {{ . }}
        secretName: letsencrypt-staging
      {{- end }}
  {{- end }}
{{- end }}
