apiVersion: v1
kind: Secret
metadata:
  name: {{ template "drone.fullname" . }}-server
  labels:
    app: {{ template "drone.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if (eq .Values.config.provider "github") }}
  DRONE_GITHUB_SECRET: {{ .Values.config.secret | b64enc }}
  {{- else if (eq .Values.config.provider "gitlab") }}
  DRONE_GITLAB_SECRET: {{ .Values.config.secret | b64enc }}
  {{- else if (eq .Values.config.provider "bitbucket-cloud") }}
  DRONE_BITBUCKET_SECRET: {{ .Values.config.secret | b64enc }}
  {{- end }}
