appVersion: 0.8.5

images:
  server:
    repository: docker.io/drone/drone
    tag: 0.8.5
    pullPolicy: IfNotPresent
  agent:
    repository: docker.io/drone/agent
    tag: 0.8.5
    pullPolicy: IfNotPresent
  dind:
    repository: docker.io/library/docker
    tag: 17.12.0-ce-dind
    pullPolicy: IfNotPresent

service:
  httpPort: 80
  type: NodePort

ingress:
  enabled: false

server:
  config:
    provider: github
    open: true
    client: ''
    secret: ''
    username: ''
  annotations: {}
  resources: {}
  affinity: {}
  nodeSelector: {}
  extraContainers: |
  extraVolumes: |

agent:
  replicas: 1
  annotations: {}
  resources: {}
  affinity: {}
  nodeSelector: {}

dind:
  enabled: true
  driver: overlay2
  resources: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

rbac:
  create: true
  apiVersion: v1

serviceAccount:
  create: true
  name: ''
