apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}-openldap
  labels:
    app: {{ template "openldap.name" . }}-openldap
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  01-organization.ldif: |
    version: 1

    dn: {{ template "openldap.openldap-dc" . }}
    objectClass: top
    objectClass: dcObject
    objectClass: organization
    o: {{ .Values.config.organization }}
    dc: {{ index (regexSplit "\\." .Values.config.domain -1) 0 }}
