apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "letsencrypt-cert.fullname" . }}
spec:
  secretName: {{ template "letsencrypt-cert.fullname" . }}
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
  commonName: {{ .Values.domains[0] }}
  dnsNames:
    {{- range $index, $domain := .Values.domains }}
    {{- (if (ne $index 0)) }}
    - {{ $domain }}
    {{- end }}
    {{- end }}
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          {{- range .Values.domains }}
          - {{ . }}
          {{- end }}
