apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dbtest.fullname" . }}-postgres-auth
  labels:
    app: {{ template "dbtest.name" . }}-postgres-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.config.password | b64enc }}
  POSTGRES_USER: {{ "postgres" | b64enc }}
