apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}-teleport
  labels:
    app: {{ template "teleport.name" . }}-teleport
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.teleport.https))) }}
      nodePort: {{ .Values.service.nodePorts.teleport.https }}
      {{- end }}
    - name: node
      port: 3022
      protocol: TCP
      targetPort: node
    - name: proxy
      port: 2023
      protocol: TCP
      targetPort: proxy
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.teleport.proxy))) }}
      nodePort: {{ .Values.service.nodePorts.teleport.proxy }}
      {{- end }}
    - name: auth
      port: 3025
      protocol: TCP
      targetPort: auth
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.teleport.auth))) }}
      nodePort: {{ .Values.service.nodePorts.teleport.auth }}
      {{- end }}
    - name: kubernetes
      port: 3026
      protocol: TCP
      targetPort: kubernetes
  selector:
    app: {{ template "teleport.name" . }}-teleport
    release: {{ .Release.Name }}
