apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "drone.fullname" . }}-agent
  labels:
    app: {{ template "drone.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "drone.name" . }}
        release: {{ .Release.Name }}
        component: agent
    spec:
      containers:
        - name: {{ template "drone.fullname" . }}-agent
          image: {{ .Values.images.agent.repository }}:{{ .Values.images.agent.tag }}
          imagePullPolicy: {{ .Values.images.agent.pullPolicy }}
