apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wikijs.fullname" . }}
  labels:
    app: {{ template "wikijs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $mongo := .Values.config.mongo }}
  {{- if $mongo.internal }}
  mongo_host: {{ template "wikijs.fullname" . }}-mongo
  {{- else }}
  mongo_host: {{ $mongo.host | quote }}
  {{- end }}
  mongo_database: {{ $mongo.database | quote }}
  mongo_port: {{ $mongo.port | quote }}
  mongo_username: {{ $mongo.username | quote }}
  email: {{ .Values.config.email | quote }}
