apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailserver.fullname" . }}-opendkim-keys
  labels:
    app: {{ template "mailserver.name" . }}-opendkim-keys
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ template "mailserver.fullname" . }}-mail.key: 'base64-encoded-DKIM-key'
