{{- if .Values.ingress.enabled }}
{{- $host := (index .Values.ingress.hosts.auth 0) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "teleport.fullname" . }}-auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
  labels:
    app: {{ template "teleport.name" . }}-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ $host.name }}
      http:
        paths:
          - path: {{ $host.path }}
            backend:
              serviceName: {{ template "teleport.fullname" . }}-teleport
              servicePort: auth
{{- end }}
