apiVersion: v1
kind: Service
metadata:
  name: {{ template "mailserver.fullname" . }}-mailserver
  labels:
    app: {{ template "mailserver.name" . }}-mailserver
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.mailserver.type }}
  {{- if (eq .Values.service.mailserver.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.mailserver.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      {{- if (eq .Values.service.mailserver.type "NodePort") }}
      nodePort: {{ .Values.service.mailserver.nodePorts.http }}
      {{- end }}
    - name: smtp-secure
      port: 465
      targetPort: smtp-secure
      {{- if (eq .Values.service.mailserver.type "NodePort") }}
      nodePort: {{ .Values.service.mailserver.nodePorts.http }}
      {{- end }}
    - name: smtp-auth
      port: 587
      targetPort: smtp-auth
      {{- if (eq .Values.service.mailserver.type "NodePort") }}
      nodePort: {{ .Values.service.mailserver.nodePorts.http }}
      {{- end }}
    - name: imap
      port: 143
      targetPort: imap
      {{- if (eq .Values.service.mailserver.type "NodePort") }}
      nodePort: {{ .Values.service.mailserver.nodePorts.http }}
      {{- end }}
    - name: imap-secure
      port: 993
      targetPort: imap-secure
      {{- if (eq .Values.service.mailserver.type "NodePort") }}
      nodePort: {{ .Values.service.mailserver.nodePorts.http }}
      {{- end }}
  selector:
    app: {{ template "mailserver.name" . }}-mailserver
    release: {{ .Release.Name }}
