apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
    app: {{ template "gluu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $redis := .Values.config.redis }}
  {{- if $redis.internal }}
  redis_host: {{ template "gluu.fullname" . }}-redis
  {{- else }}
  redis_host: {{ $redis.host | quote }}
  {{- end }}
  redis_port: {{ $redis.port | quote }}
  redis_username: {{ $redis.username | quote }}
  city: {{ .Values.config.city | quote }}
  country_code: {{ .Values.config.countryCode | quote }}
  email: {{ .Values.config.email | quote }}
  hostname: {{ .Values.config.hostname | quote }}
  organization: {{ .Values.config.organization | quote }}
  state: {{ .Values.config.state | quote }}
