apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gluu.fullname" . }}
  labels:
    app: {{ template "gluu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $postgres := .Values.config.postgres }}
  {{- if $postgres.internal }}
  postgres_host: {{ template "gluu.fullname" . }}-postgres
  {{- else }}
  postgres_host: {{ $postgres.host | quote }}
  {{- end }}
  postgres_database: {{ $postgres.database | quote }}
  postgres_port: {{ $postgres.port | quote }}
  postgres_username: {{ $postgres.username | quote }}
  {{- $redis := .Values.config.redis }}
  {{- if $redis.internal }}
  redis_host: {{ template "gluu.fullname" . }}-redis
  {{- else }}
  redis_host: {{ $redis.host | quote }}
  {{- end }}
  redis_port: {{ $redis.port | quote }}
  redis_username: {{ $redis.username | quote }}
  city: {{ .Values.config.city | quote }}
  country_code: {{ .Values.config.countryCode | quote }}
  email: {{ .Values.config.email | quote }}
  hostname: {{ .Values.config.hostname | quote }}
  openid_url: {{ template "gluu.oxauth_url" . }}/oxauth
  organization: {{ .Values.config.organization | quote }}
  oxauth_hostname: {{ .Values.config.oxauthHostname | quote }}
  oxauth_url: {{ template "gluu.oxauth_url" . }}
  oxpassport_hostname: {{ .Values.config.oxpassportHostname | quote }}
  oxshibboleth_hostname: {{ .Values.config.oxshibbolethHostname | quote }}
  oxtrust_hostname: {{ .Values.config.oxtrustHostname | quote }}
  state: {{ .Values.config.state | quote }}
