images:
  volback:
    repository: codejamninja/volback
    tag: 3.0.0
    pullPolicy: IfNotPresent

config:
  awsAccessKey: ''
  awsSecretKey: ''
  forgetArgs: '--keep-last 3'
  resticPassword: 'volback'
  serverPsk: 'volback'
  targetUrl: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

serviceAccount:
  create: true
  name: ''
