images:
  oxtrust:
    repository: gluufederation/oxtrust
    tag: 3.1.5_04
    pullPolicy: IfNotPresent
  oxshibboleth:
    repository: gluufederation/oxshibboleth
    tag: 3.1.5_03
    pullPolicy: IfNotPresent
  oxpassport:
    repository: gluufederation/oxpassport
    tag: 3.1.5_03
    pullPolicy: IfNotPresent
  oxauth:
    repository: gluufederation/oxauth
    tag: 3.1.5_04
    pullPolicy: IfNotPresent
  init:
    repository: gluufederation/config-init
    tag: 3.1.5_05
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
  opendj:
    repository: gluufederation/opendj
    tag: 3.1.5_03
    pullPolicy: IfNotPresent
  gg-konga:
    repository: codejamninja/gg-konga
    tag: 0.0.1
    pullPolicy: IfNotPresent

config:
  city: Austin
  countryCode: US
  email: email@example.com
  hostname: ''
  organization: Gluu
  password: pass
  state: Texas
  postgres:
    database: kong
    host: ''
    internal: true
    password: postgres
    port: 5432
    url: ''
    username: postgres
  redis:
    host: ''
    internal: true
    password: ''
    port: 6379
    url: ''
    username: ''
  openidUri: 'https://accounts.gluu.org/oxauth'
  secret: 'some-secret'

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    oxauth:
      http: ''
    oxpassport:
      http: ''
    oxshibboleth:
      http: ''
    oxtrust:
      http: ''
    gg-konga:
      http: ''

ingress:
  enabled: false
  tls: false
  issuer:
    name: letsencrypt-staging
  hosts:
    gluu:
      - name: ''
        path: /
    gg-konga:
      - name: ''
        path: /

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 10Gi
  storageClass: ''
  volbackBackup: false

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
