apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "volback.fullname" . }}-volback
  labels:
    app: {{ template "volback.name" . }}-volback
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "volback.fullname" . }}-volback
subjects:
  - kind: ServiceAccount
    name: {{ template "volback.fullname" . }}-volback
    namespace: kube-system
  - kind: ServiceAccount
    name: {{ template "volback.fullname" . }}-volback
    namespace: volback

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "volback.fullname" . }}-volback
  labels:
    app: {{ template "volback.name" . }}-volback
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ['']
    resources:
      - pods/log
      - pods/exec
      - persistentvolumeclaims
      - namespaces
      - pods
    verbs:
      - create
      - delete
      - get
      - post
      - list
