apiVersion: v1
kind: Secret
metadata:
  name: {{ template "volback.fullname" . }}
  labels:
    app: {{ template "volback.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  aws_secret_key: {{ .Values.config.awsSecretKey | b64enc }}
  restic_password: {{ .Values.config.resticPassword | b64enc }}
  volback_server_psk: {{ .Values.config.volbackServerPsk | b64enc }}
