apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "teleport.fullname" . }}-teleport
  labels:
    app: {{ template "teleport.name" . }}-teleport
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  teleport.yaml: |
    teleport:
      log:
        output: stderr
        severity: DEBUG
      data_dir: /var/lib/teleport
      storage:
        type: dir
    auth_service:
      enabled: yes
      authentication:
        type: oidc
      public_addr: {{ template "teleport.hostname" . }}:3025
      cluster_name: {{ template "teleport.hostname" . }}
    ssh_service:
      enabled: yes
      public_addr: {{ template "teleport.hostname" . }}:3022
    proxy_service:
      enabled: yes
      public_addr: {{ template "teleport.hostname" . }}
      web_listen_addr: 0.0.0.0:3080
      listen_addr: 0.0.0.0:3023
      https_key_file: /var/lib/certs/tls.key
      https_cert_file: /var/lib/certs/tls.crt
