apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dbtest.fullname" . }}-dbtest
  labels:
    app: {{ template "dbtest.name" . }}-dbtest
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "dbtest.name" . }}-dbtest
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "dbtest.name" . }}-dbtest
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "dbtest.fullname" . }}-dbtest
          image: {{ .Values.images.dbtest.repository }}:{{ .Values.images.dbtest.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 3000
          env: []
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
