apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "dbtest.fullname" . }}-nginx
  labels:
    app: {{ template "dbtest.name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "dbtest.name" . }}-nginx
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "dbtest.fullname" . }}-nginx
          image: {{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          ports:
            - name: container
              containerPort: 80
          volumeMounts:
            - name: test
              mountPath: '/data'
              subPath: test
          env: []
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: test
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "dbtest.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
