images:
  mailserver:
    repository: tvial/docker-mailserver
    tag: release-v6.2.1

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  spoofProtection: true
  enableSrs: true
  defaultRelayHost: ''
  clamav:
    enabled: false
  mailserver:
    baseUrl: ''
    hostname: ''
  dovecot:
    passAttrs: ''
    passFilter: ''
    tls: ''
    userAttrs: ''
    userFilter: ''
  enableManagesieve: ''
  fail2ban:
    enabled: false
  fetchmail:
    enabled: false
    poll: ''
  ldapBindDn: ''
  ldapBindPw: ''
  ldap:
    enabled: false
    queryFilterAlias: ''
    queryFilterDomain: ''
    queryFilterGroup: ''
    queryFilterUser: ''
    searchBase: ''
    serverHost: ''
    startTls: ''
  postfixMailboxSizeLimit: ''
  postfixMessageSizeLimit: ''
  postgrey:
    autoWhitelistClients: ''
    delay: ''
    enabled: false
    maxAge: ''
    text: ''
  postmasterAddress: ''
  saslPasswd: ''
  saslauthd:
    enabled: false
    ldapBindDn: ''
    ldapFilter: ''
    ldapPassword: ''
    ldapSearchBase: ''
    ldapServer: ''
    ldapSsl: false
    mechOptions: ''
    mechanisms: ''
  spamassassin:
    enabled: false
    kill: ''
    shortcircuitBayesHam: ''
    shortcircuitBayesSpam: ''
    spamSubject: ''
    tag2: ''
    tag: ''
  srs:
    domainname: ''
    enabled: false
    excludeDomains: ''
    secret: ''
    senderClasses: ''
  virusmailsDeleteDelay: ''

service:
  mailserver:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''

ingress:
  mailserver:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  velero:
    enabled: false
  stash:
    enabled: false
    keepLast: 30
    paused: false
    repository: stash-stash
    schedule: '0 0 * * *'
    restore:
      snapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
