apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-mysql
  labels:
    app: {{ template "mysql.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  my-config.cnf: {{ .Values.config.mysql.config | quote }}
