images:
  sks:
    repository: zhusj/sks
    tag: latest
    pullPolicy: IfNotPresent

config:

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    sks:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    sks:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
  existingClaim: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
