apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "onlyoffice.fullname" . }}-onlyoffice
  labels:
    app: {{ template "onlyoffice.name" . }}-onlyoffice
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "onlyoffice.name" . }}-onlyoffice
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "onlyoffice.fullname" . }}-onlyoffice
          image: {{ .Values.images.onlyoffice.repository }}:{{ .Values.images.onlyoffice.tag }}
          imagePullPolicy: {{ .Values.images.onlyoffice.pullPolicy }}
          ports:
            - name: container
              containerPort: 80
          volumeMounts:
            - name: data
              mountPath: '/var/lib/onlyoffice/documentserver/App_Data/cache/files'
              subPath: cache
          env: []
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "onlyoffice.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
