apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bastion.fullname" . }}
  labels:
    app: {{ template "bastion.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  authorizedKeys: {{ .Values.config.authorizedKeys | quote }}
  users: {{ .Values.config.users | quote }}
  authMechanism: {{ .Values.config.authMechanism | quote }}
