{{- if .Values.config.kibana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  kibana_password: {{ .Values.config.kibana.password | b64enc }}
{{- end }}
