apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "teleport.fullname" . }}-teleport
  labels:
    app: {{ template "teleport.name" . }}-teleport
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "teleport.name" . }}-teleport
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "teleport.fullname" . }}-teleport
          image: {{ .Values.images.teleport.repository }}:{{ .Values.images.teleport.tag }}
          imagePullPolicy: {{ .Values.images.teleport.pullPolicy }}
          ports:
            - name: node
              containerPort: 3022
            - name: proxy
              containerPort: 3023
            - name: auth
              containerPort: 3025
            - name: kubernetes
              containerPort: 3026
            - name: https
              containerPort: 3080
          volumeMounts:
            - name: config
              mountPath: /etc/teleport
            - name: data
              mountPath: /var/lib/teleport
              subPath: data
            {{- if (and $.Values.ingress.enabled $.Values.ingress.tls) }}
            - name: certs
              mountPath: /var/lib/certs
            {{- end }}
          env: []
          livenessProbe:
            tcpSocket:
              port: proxy
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: proxy
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "teleport.fullname" . }}-teleport
        {{- if (and $.Values.ingress.enabled $.Values.ingress.tls) }}
        - name: certs
          secret:
            secretName: {{ template "teleport.certificate" . }}
        {{- end }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "teleport.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
