apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "onetimesecret.fullname" . }}-onetimesecret
  labels:
    app: {{ template "onetimesecret.name" . }}-onetimesecret
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "onetimesecret.name" . }}-onetimesecret
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "onetimesecret.fullname" . }}-onetimesecret
          image: {{ .Values.images.onetimesecret.repository }}:{{ .Values.images.onetimesecret.tag }}
          imagePullPolicy: {{ .Values.images.onetimesecret.pullPolicy }}
          ports:
            - name: container
              containerPort: 7143
          volumeMounts:
            - name: data
              mountPath: '/redis'
              subPath: redis
          env: []
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "onetimesecret.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
