apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bitwardenrs.fullname" . }}
  labels:
    app: {{ template "bitwardenrs.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  admin_token: {{ .Values.config.adminToken | quote }}
  signups_allowed: {{ .Values.config.signupsAllowed | quote }}
  smpt_host: {{ .Values.config.smpt.host | quote }}
  smtp_from: {{ .Values.config.smtp.from | quote }}
  smtp_port: {{ .Values.config.smtp.port | quote }}
  smtp_ssl: {{ .Values.config.smtp.ssl | quote }}
  smtp_username: {{ .Values.config.smtp.username | quote }}
  {{- $postgres := .Values.config.postgres }}
  {{- if $postgres.internal }}
  postgres_host: {{ template "bitwardenrs.fullname" . }}-postgres
  {{- else }}
  postgres_host: {{ $postgres.host | quote }}
  {{- end }}
  postgres_database: {{ $postgres.database | quote }}
  postgres_port: {{ $postgres.port | quote }}
  postgres_username: {{ $postgres.username | quote }}
  {{- if .Values.config.pgadmin.enabled }}
  pgadmin_email: {{ .Values.config.pgadmin.email | quote }}
  {{- end }}
