apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch-auth
  labels:
    app: {{ template "elasticsearch.name" . }}-elasticsearch-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.config.password | b64enc }}
  ADMIN_USERNAME: {{ "elasticsearch" | b64enc }}
  READALL_PASSWORD: {{ .Values.config.password | b64enc }}
  READALL_USERNAME: {{ "elasticsearch" | b64enc }}
  sg_config.yml: |
    {}
  sg_internal_users.yml: |
    {}
  sg_roles_mapping.yml: |
    {}
  sg_action_groups.yml: |
    {}
  sg_roles.yml: |
    {}
