images:
  huginn:
    repository: huginn/huginn
    tag: 50f13d586aad1136368ffad087adcf1b3b52b469
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent

config:
  postgres:
    host: ''
    database: huginn
    password: ''
    port: 5432
    url: ''
    username: ''

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    huginn:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    huginn:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  cachingMode: None
  diskName: ''
  diskURI: ''
  enabled: false
  existingClaim: ''
  fsType: ext4
  kind: Shared
  readOnly: false
  secretName: ''
  secretNamespace: ''
  shareName: ''
  size: 10Gi
  type: persistentVolumeClaim
  volumeId: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
