apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-elasticsearch
  labels:
    app: {{ template "elasticsearch.name" . }}-elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  user.conf: {{ .Values.config.customConfig | quote }}
