apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: {{ template "stash.fullname" . }}-mysql
  labels:
    app: {{ template "stash.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backend:
    {{ .Values.config.type }}:
      {{- if (or (eq "gcs" .Values.config.type) (eq "s3" .Values.config.type)) }}
      bucket: {{ .Values.config.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.config.type) }}
      endpoint: {{ .Values.config.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.config.type) }}
      container: {{ .Values.config.container | quote }}
      {{- end }}
      prefix: '{{ .Values.config.prefix }}/${TARGET_NAMESPACE}/mysql'
    storageSecretName: {{ template "stash.fullname" . }}-backup
  task:
    name: ${TARGET_APP_RESOURCE}-backup-${TARGET_APP_VERSION}
  schedule: {{ .Values.config.schedule | quote }}
  retentionPolicy:
    name: retention-policy
    keepLast: {{ .Values.config.keepLast }}
    prune: true
