apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.version | quote }}
  configSource:
    configMap:
      name: {{ template "postgres.fullname" . }}-postgres
  standbyMode: {{ .Values.config.standbyMode | quote }}
  {{- if .Values.config.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if (not (empty .Values.config.backup.enabled)) }}
  backupSchedule:
    cronExpression: {{ .Values.config.backup.cron | quote }}
    storageSecretName: {{ template "postgres.fullname" . }}-postgres
    {{ .Values.config.backup.type }}:
      {{- if (or (eq "gcs" .Values.config.backup.type) (eq "s3" .Values.config.backup.type)) }}
      bucket: {{ .Values.config.backup.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.config.backup.type) }}
      endpoint: {{ .Values.config.backup.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.config.backup.type) }}
      container: {{ .Values.config.backup.container | quote }}
      {{- end }}
      prefix: {{ .Values.config.backup.prefix | quote }}
  {{- end }}
  {{- if (not (empty .Values.config.restoreFromSnapshot)) }}
  init:
    snapshotSource:
      name: {{ .Values.config.restoreFromSnapshot | quote }}
      namespace: {{ .Release.Namespace }}
  {{- end }}
  serviceTemplate:
    metadata:
      annotations:
        passMe: ToService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name: http
          port: 5432
          targetPort: http
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres.port))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres.port }}
          {{- end }}
  replicaServiceTemplate:
    annotations:
      passMe: ToReplicaService
    spec:
      type: {{ .Values.service.postgres.type }}
      {{- if (or (eq .Values.service.postgres.type "LoadBalancer") (eq .Values.service.postgres.type "NodePort")) }}
      externalTrafficPolicy: {{ .Values.service.postgres.externalTrafficPolicy }}
      {{- end }}
      ports:
        - name:  http
          port:  5432
          targetPort: http
          {{- if (and (eq .Values.service.postgres.type "NodePort") (not (empty .Values.service.postgres.nodePorts.postgres.port))) }}
          nodePort: {{ .Values.service.postgres.nodePorts.postgres.port }}
          {{- end }}
  updateStrategy:
    type: RollingUpdate
