apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "navyanginx.fullname" . }}
  labels:
    app: {{ template "navyanginx.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  hello: {{ .Values.config.hello | quote }}
