apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-mysql
  labels:
    app: {{ template "mysql.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if (eq (substr 0 1 .Values.config.version) "8") }}
  my-config.cnf: {{ ((empty .Values.config.customConfig) | ternary "[mysqld]\ndefault_authentication_plugin = mysql_native_password" .Values.config.customConfig) | quote }}
  {{- else }}
  my-config.cnf: {{ .Values.config.customConfig | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}-mysql-init
  labels:
    app: {{ template "mysql.name" . }}-mysql-init
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  init.sql: ''
