images:
  gitlab:
    repository: store/gitlab/gitlab-ce
    tag: 10.2.4-ce.0
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent

config:
  password: ''
  baseUrl: ''
  postgres:
    database: gitlab
    host: ''
    internal: true
    password: postgres
    port: 5432
    url: ''
    username: postgres
  redis:
    host: ''
    internal: true
    password: ''
    port: 6379
    url: ''
    username: ''

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    gitlab:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    gitlab:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  cachingMode: None
  diskName: ''
  diskURI: ''
  enabled: false
  existingClaim: ''
  fsType: ext4
  kind: Shared
  readOnly: false
  secretName: ''
  secretNamespace: ''
  shareName: ''
  size: 10Gi
  type: persistentVolumeClaim
  volumeId: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
