{{- if (not .Values.config.postgres.host) }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "huginn.fullname" . }}-postgres
  labels:
    app: {{ template "huginn.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "huginn.name" . }}-postgres
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "huginn.fullname" . }}-postgres
          image: {{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          ports:
            - name: container
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ template "huginn.fullname" . }}
                  key: postgres_database
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ template "huginn.fullname" . }}
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "huginn.fullname" . }}
                  key: postgres_password
          livenessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          {{- if (eq .Values.persistence.type "persistentVolumeClaim") }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "huginn.fullname" . ) }}
          {{- elif (eq .Values.persistence.type "awsElasticBlockStore") }}
          awsElasticBlockStore:
            volumeID: {{ .Values.persistence.volumeId }}
            fsType: {{ .Values.persistence.fsType }}
          {{- elif (eq .Values.persistence.type "azureDisk") }}
          azureDisk:
            cachingMode: {{ .Values.persistence.cachingMode }}
            diskName: {{ .Values.persistence.diskName }}
            diskURI: {{ .Values.persistence.diskUri }}
            fsType: {{ .Values.persistence.fsType }}
            kind: {{ .Values.persistence.diskKind }}
            readOnly: {{ .Values.persistence.readOnly | quote }}
          {{- elif (eq .Values.persistence.type "azureFile") }}
          azureFile:
            readOnly: {{ .Values.persistence.readOnly | quote }}
            secretName: {{ .Values.persistence.secretName }}
            shareName: {{ .Values.persistence.shareName }}
            {{- if (not (empty .Values.persistence.secretNamespace)) }}
            secretNamespace: {{ .Values.persistence.secretNamespace }}
            {{- end }}
          {{- elif (eq .Values.persistence.type "cephfs") }}
          cephfs:
          {{- elif (eq .Values.persistence.type "flocker") }}
          flocker:
          {{- elif (eq .Values.persistence.type "gcePersistentDisk") }}
          gcePersistentDisk:
          {{- elif (eq .Values.persistence.type "glusterfs") }}
          glusterfs:
          {{- elif (eq .Values.persistence.type "local") }}
          local:
          {{- elif (eq .Values.persistence.type "nfs") }}
          nfs:
          {{- elif (eq .Values.persistence.type "portworxVolume") }}
          portworxVolume:
          {{- elif (eq .Values.persistence.type "quobyte") }}
          quobyte:
          {{- elif (eq .Values.persistence.type "rbd") }}
          rbd:
          {{- elif (eq .Values.persistence.type "scaleIO") }}
          scaleIO:
          {{- elif (eq .Values.persistence.type "storageOS") }}
          storageOS:
          {{- elif (eq .Values.persistence.type "vsphereVolume") }}
          vsphereVolume:
          {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
