{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "taiga.fullname" $ }}
  labels:
    app: {{ template "taiga.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: /api
            backend:
              serviceName: {{ template "taiga.fullname" $ }}-back
              servicePort: 80
          - path: /
            backend:
              serviceName: {{ template "taiga.fullname" $ }}-front
              servicePort: 80
---
{{- end }}
{{- end }}
