{{- $email := .Values.config.email }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "taiga.fullname" . }}
  labels:
    app: {{ template "taiga.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  email_smtp_password: {{ $email.smtp.password | b64enc }}
