apiVersion: v1
appVersion: v0.9.0-rc.4
description: Stash by AppsCode - Backup your Kubernetes Volumes
home: https://appscode.com/products/stash/
icon: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
maintainers:
- email: support@appscode.com
  name: appscode
name: stash
sources:
- https://github.com/stashed/stash
version: v0.9.0-rc.4
