images:
  kibana:
    repository: kibana
    tag: 7.3.0
    pullPolicy: IfNotPresent

config:
  commonConfig: ''
  dataConfig: ''
  kibana: true
  masterConfig: ''
  prometheus: false
  replicas: 1
  secret: ''
  updateStrategy: RollingUpdate
  version: 6.4.0

service:
  kibana:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      kibana:
        http: ''
  elasticsearch:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      elasticsearch:
        port: ''

ingress:
  certificate: ''
  enabled: false
  tls: false
  issuer:
    name: letsencrypt-staging
  hosts:
    kibana:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    # keepLast: 5
    prefix: ''
    resticPassword: pass
    restoreSnapshot: ''
    schedule: '@midnight'
    type: s3

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
