{{- if .Values.persistence.stash.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: BackupBatch
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  repository:
    name: {{ .Values.persistence.stash.repository }}
  paused: {{ .Values.persistence.stash.paused }}
  schedule: {{ .Values.persistence.stash.schedule | quote }}
  retentionPolicy:
    name: retention-policy
    keepLast: {{ .Values.persistence.stash.keepLast }}
    prune: true
  members:
    - target:
        ref:
          apiVersion: apps/v1
          kind: AppBinding
          name: {{ template "postgres.fullname" . }}-postgres
      task:
        name: postgres-backup-11.1
{{- end }}
