apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "postgres.fullname" . }}-postgres
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "postgres.fullname" . }}-postgres
  labels:
    app: {{ template "postgres.name" . }}-postgres
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '0'
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups: ['']
    resources:
      - statefulsets
    verbs:
      - get
  - apiGroups: ['']
    resources:
      - pods
    verbs:
      - list
      - patch
  - apiGroups: ['']
    resources:
      - repositories.stash.appscode.com
    verbs:
      - get
      - create
  - apiGroups: ['']
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
