apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "webdav.fullname" . }}
  labels:
    app: {{ template "webdav.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  username: {{ .Values.config.username | quote }}
