images:
  phpmyadmin:
    repository: phpmyadmin/phpmyadmin
    tag: latest
    pullPolicy: IfNotPresent

config:
  customConfig: ''
  phpmyadmin: true
  prometheus: false
  restoreFromSnapshot: ''
  standbyMode: ''
  version: 8.0-v2
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    cron: '@daily'
    enabled: false
    endpoint: ''
    googleProjectId: ''
    googleServiceKey: ''
    prefix: ''
    type: ''

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    phpmyadmin:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    phpmyadmin:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 10Gi

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
