images:
  phpmyadmin:
    repository: phpmyadmin/phpmyadmin
    tag: 4.7
    pullPolicy: IfNotPresent

config:
  customConfig: ''
  phpmyadmin: true
  prometheus: false
  secret: ''
  standbyMode: hot
  updateStrategy: RollingUpdate
  version: 8.0.3

service:
  phpmyadmin:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      phpmyadmin:
        http: ''
  mysql:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      mysql:
        port: ''

ingress:
  certificate: ''
  enabled: false
  tls: false
  issuer:
    name: letsencrypt-staging
  hosts:
    phpmyadmin:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    # keepLast: 5
    prefix: ''
    resticPassword: pass
    restoreSnapshot: ''
    schedule: '@every 1d'
    type: s3

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
