images:
  openldap:
    repository: osixia/openldap
    tag: 1.2.4
  phpldapadmin:
    repository: osixia/phpldapadmin
    tag: 0.9.0

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  organization: 'Example Inc.'
  domain: example.org
  debug: false
  openldap:
    baseUrl: ''
    hostname: ''
  phpldapadmin:
    enabled: true
    ldapHosts: ''
    serverAdmin: ''

service:
  openldap:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  phpldapadmin:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''

ingress:
  openldap:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging
  phpldapadmin:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  velero:
    enabled: false
  stash:
    enabled: false
    keepLast: 30
    paused: false
    repository: stash-stash
    schedule: '0 0 * * *'
    restore:
      snapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
