apiVersion: v1
kind: Service
metadata:
  name: {{ template "gluu.fullname" . }}-opendj
  labels:
    app: {{ template "gluu.name" . }}-opendj
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: admin
      port: 4444
      targetPort: admin
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.opendj.http))) }}
      nodePort: {{ .Values.service.nodePorts.opendj.http }}
      {{- end }}
    - name: ldaps
      port: 1636
      targetPort: ldaps
    - name: ldap
      port: 1389
      targetPort: ldap
    - name: replication
      port: 8989
      targetPort: replication
  selector:
    app: {{ template "gluu.name" . }}-opendj
    release: {{ .Release.Name }}
