{{- if (and .Values.config.jitsi.enabled (not .Values.config.jitsi.domain)) }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "rocketchat.fullname" . }}-jitsi
  labels:
    app: {{ template "rocketchat.name" . }}-jitsi
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "rocketchat.name" . }}-jitsi
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "rocketchat.fullname" . }}-jitsi
          image: {{ .Values.images.jitsi.repository }}:{{ .Values.images.jitsi.tag }}
          imagePullPolicy: {{ .Values.images.jitsi.pullPolicy }}
          ports:
            - name: container
              containerPort: 3002
{{- end }}
