{{- if (not (or .Values.config.database.url .Values.config.database.host)) }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "rocketchat.fullname" . }}-mongo
  labels:
    app: {{ template "rocketchat.name" . }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "rocketchat.name" . }}-mongo
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "rocketchat.fullname" . }}-mongo
          image: {{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}
          imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
          ports:
            - name: container
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
              subPath: mongo
         env:
           - name: MONGO_INITDB_DATABASE
             value: rocketchat
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "rocketchat.fullname" . ) }}
          {{- else }}
          emptyDir: {}
          {{- end -}}
{{- end }}
