apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "rocketchat.fullname" . }}-rocketchat
  labels:
    app: {{ template "rocketchat.name" . }}-rocketchat
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "rocketchat.name" . }}-rocketchat
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "rocketchat.fullname" . }}-rocketchat
          image: {{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          ports:
            - name: container
              containerPort: 3002
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: database_url
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: email_smtp_host
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: email_smtp_port
            - name: SMTP_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: email_smtp_username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: email_smtp_password
            - name: FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: email_from
            - name: JITSI_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: jitsi_enabled
            - name: JITSI_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: jitsi_domain
            - name: JITSI_URL_ROOM_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: jitsi_url_room_prefix
            - name: JITSI_OPEN_NEW_WINDOW
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: jitsi_open_new_window
            - name: JITSI_ENABLE_CHANNELS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: jitsi_enable_channels
            - name: JITSI_CHROME_EXTENSION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: jitsi_chrome_extension
            - name: WEBRTC_ENABLE_CHANNELS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: webrtc_enable_channels
            - name: WEBRTC_ENABLE_PRIVATE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: webrtc_enable_private
            - name: WEBRTC_ENABLE_DIRECT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "rocketchat.fullname" . }}
                  key: webrtc_enable_direct
