images:
  bastion:
    repository: codejamninja/oh-my-zsh
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    bastion:
      ssh: ''

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  cachingMode: None
  diskName: ''
  diskURI: ''
  enabled: false
  existingClaim: ''
  fsType: ext4
  kind: Shared
  readOnly: false
  secretName: ''
  secretNamespace: ''
  shareName: ''
  size: 10Gi
  type: persistentVolumeClaim
  volumeId: ''
