apiVersion: v1
kind: Service
metadata:
  name: {{ template "bastion.fullname" . }}-bastion
  labels:
    app: {{ template "bastion.name" . }}-bastion
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: container
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.bastion.ssh))) }}
      nodePort: {{ .Values.service.nodePorts.bastion.ssh }}
      {{- end }}
  selector:
    app: {{ template "bastion.name" . }}-bastion
    release: {{ .Release.Name }}
