images:
  webdav:
    repository: bytemark/webdav
    tag: 2.4
    pullPolicy: IfNotPresent

config:
  username: 'admin'
  password: 'pass'

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    webdav:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    webdav:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
  existingClaim: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
