apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mailserver.fullname" . }}-mailserver
  labels:
    app: {{ template "mailserver.name" . }}-mailserver
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postfix-accounts.cf: |
    user1@{{ template "mailserver.fullname" . }}|{SHA512-CRYPT}$6$2YpW1nYtPBs2yLYS$z.5PGH1OEzsHHNhl3gJrc3D.YMZkvKw/vp.r5WIiwya6z7P/CQ9GDEJDr2G2V0cAfjDFeAQPUoopsuWPXLk3u1

  postfix-virtual.cf: |
    alias1@{{ template "mailserver.fullname" . }} user1@{{ template "mailserver.fullname" . }}

  postfix-main.cf: |
    smtpd_upstream_proxy_protocol = haproxy

  dovecot.cf: |
    service stats {
      unix_listener stats-reader {
        group = docker
        mode = 0666
      }
      unix_listener stats-writer {
        group = docker
        mode = 0666
      }
    }
    service imap-login {
      inet_listener imaps {
        haproxy = yes
      }
    }

  SigningTable: |
    *@{{ template "mailserver.fullname" . }} mail._domainkey.{{ template "mailserver.fullname" . }}

  KeyTable: |
    mail._domainkey.{{ template "mailserver.fullname" . }} {{ template "mailserver.fullname" . }}:mail:/etc/opendkim/keys/{{ template "mailserver.fullname" . }}-mail.key

  TrustedHosts: |
    127.0.0.1
    localhost

  user-patches.sh: |
    #!/bin/bash

  fetchmail.cf: |
