apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "mongo.fullname" . }}-mongo
  labels:
    app: {{ template "mongo.name" . }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mongo.fullname" . }}-mongo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "mongo.fullname" . }}-mongo
  labels:
    app: {{ template "mongo.name" . }}-mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ['']
    resources:
      - statefulsets
    verbs:
      - get
  - apiGroups: ['']
    resources:
      - pods
    verbs:
      - list
      - patch
  - apiGroups: ['']
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
