name: nginx
home: https://www.nginx.com
icon: https://cdn-1.wp.nginx.com/wp-content/uploads/2018/03/icon-NGINX-OSS.svg
version: 0.1.0
appVersion: 1.15.3
description: |
  a web server which can also be used as a reverse proxy, load balancer, mail proxy and HTTP cache
keywords:
  - file-server
  - http-cache
  - load-balancer
  - mail-proxy
  - proxy
  - reverse-proxy
  - server
sources:
  - http://hg.nginx.org/nginx
maintainers:
  - name: 'Jam Risser'
    email: jam@codejam.ninja
