image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  hosts: []

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    http: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
