{{- if (and .Values.ingress.enabled .Values.ingress.ssl) }}
{{- $host := (index .Values.ingress.hosts 0) }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "rocketchat.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
  commonName: {{ $host.name }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - {{ $host.name }}
{{- end }}
