apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  email_smtp_password: {{ .Values.config.email.smtp.password }}
  {{- if .Values.config.database.url) }}
  database_url: {{ .Values.config.database.url }}
  {{- else if (and .Values.config.database.username .Values.config.database.password) }}
  database_url: mongodb://{{ .Values.config.database.username }}:{{ .Values.config.database.password }}@{{ .Values.config.database.host }}:{{ .Values.config.database.port }}/{{ .Values.config.database.name }}
  {{- end }}
