apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app: {{ template "rocketchat.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- $mongo := .Values.config.mongo }}
  {{- if (or $mongo.url $mongo.username $mongo.password) }}
  mongo_url: "hi"
  {{- end }}
  email_smtp_password: {{ .Values.config.email.smtp.password | b64enc }}
