apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  organization: {{ .Values.config.organization | quote }}
  domain: {{ .Values.config.domain | quote }}
