apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  domain: {{ .Values.config.domain | quote }}
  organization: {{ .Values.config.organization | quote }}
  phpldapadmin_server_admin: {{ .Values.config.phpldapadmin.serverAdmin | quote }}
  phpldapadmin_ldap_hosts: |
    - {{ template "openldap.openldap-hostname" . }}:
        - server:
            - tls: false
        - login:
            - bind_id: cn=admin,{{ template "openldap.openldap-dc" . }}
