images:
  sonarqube:
    repository: sonarqube
    tag: 7.7-community
    pullPolicy: IfNotPresent
  postgres:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent

config:
  postgres:
    database: sonarqube
    host: ''
    internal: true
    password: postgres
    port: 5432
    url: ''
    username: postgres

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    sonarqube:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    sonarqube:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  cachingMode: None
  diskName: ''
  diskURI: ''
  enabled: false
  existingClaim: ''
  fsType: ext4
  kind: Shared
  readOnly: false
  secretName: ''
  secretNamespace: ''
  shareName: ''
  size: 10Gi
  type: persistentVolumeClaim
  volumeId: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
