apiVersion: v1
kind: Service
metadata:
  name: {{ template "dbtest.fullname" . }}-dbtest
  labels:
    app: {{ template "dbtest.name" . }}-dbtest
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.dbtest.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.dbtest.type }}
  {{- if (or (eq .Values.service.dbtest.type "LoadBalancer") (eq .Values.service.dbtest.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.dbtest.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: container
      {{- if (and (eq .Values.service.dbtest.type "NodePort") (not (empty .Values.service.dbtest.nodePorts.http))) }}
      nodePort: {{ .Values.service.dbtest.nodePorts.http }}
      {{- end }}
  selector:
    app: {{ template "dbtest.name" . }}-dbtest
    release: {{ .Release.Name }}
