images:
  taigaBack:
    repository: ipedrazas/taiga-back
    tag: latest
    pullPolicy: IfNotPresent
  taigaFront:
    repository: ipedrazas/taiga-front
    tag: latest
    pullPolicy: IfNotPresent

config:
  hostname: ''
  email:
    from: email@example.com
    smtp:
      host: ''
      password: ''
      port: 25
      username: ''

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    taigaBack:
      http: ''
    taigaFront:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    taiga:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 10Gi
  storageClass: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
