{{- if .Values.config.pgadmin.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "postgres.fullname" . }}-pgadmin
  labels:
    app: {{ template "postgres.name" . }}-pgadmin
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "postgres.name" . }}-pgadmin
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "postgres.fullname" . }}-pgadmin
          image: {{ .Values.images.pgadmin.repository }}:{{ .Values.images.pgadmin.tag }}
          imagePullPolicy: {{ .Values.images.pgadmin.pullPolicy }}
          ports:
            - name: container
              containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://{{ template "elasticsearch.fullname" . }}-elasticsearch:9200
          livenessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.liveness | indent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: container
{{ toYaml .Values.probes.readiness | indent 12 }}
{{- end }}
