{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nginx.fullname" $ }}
  labels:
    app: {{ template "nginx.name" $ }}
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  rules:
    - host: {{ .name }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "nginx.fullname" $ }}
              servicePort: 80
---
{{- end }}
{{- end }}
