images:
  pgadmin:
    repository: dpage/pgadmin4
    tag: latest
    pullPolicy: IfNotPresent

config:
  awsAccessKey: ''
  awsSecretKey: ''
  azureAccountKey: ''
  azureAccountName: ''
  backup: ''
  backupContainer: ''
  backupCron: '@daily'
  bucket: ''
  bucketEndpoint: ''
  bucketPrefix: ''
  googleProjectId: ''
  googleServiceKey: ''
  pgadmin: true
  pgadminEmail: 'admin'
  pgadminPassword: 'admin'
  prometheus: false
  restoreFromSnapshot: ''
  standbyMode: ''
  userConfig: ''
  version: 10.2-v2

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  nodePorts:
    pgadmin:
      http: ''

ingress:
  enabled: false
  tls: false
  hosts:
    pgadmin:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  size: 10Gi

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
