images:
  pgadmin:
    repository: dpage/pgadmin4
    tag: latest
    pullPolicy: IfNotPresent

config:
  customConfig: ''
  pgadmin: true
  prometheus: false
  secret: ''
  standbyMode: hot
  updateStrategy: RollingUpdate
  version: 11.1

service:
  pgadmin:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      pgadmin:
        http: ''
  postgres:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      postgres:
        port: ''

ingress:
  enabled: false
  tls: false
  hosts:
    pgadmin:
      - name: ''
        path: /

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  backup:
    awsAccessKey: ''
    awsSecretKey: ''
    azureAccountKey: ''
    azureAccountName: ''
    bucket: ''
    container: ''
    enabled: false
    endpoint: s3.amazonaws.com
    googleProjectId: ''
    googleServiceKey: ''
    # keepLast: 5
    prefix: ''
    resticPassword: pass
    restoreSnapshot: ''
    schedule: '@every 1d'
    type: s3

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
