image:
  server:
    repository: docker.io/drone/drone
    tag: 0.8.5
    pullPolicy: IfNotPresent
  agent:
    repository: docker.io/drone/agent
    tag: 0.8.5
    pullPolicy: IfNotPresent

server:
  affinity: {}
  nodeSelector: {}
  schedulerName: unknown
