apiVersion: v1
kind: Service
metadata:
  name: {{ template "openldap.fullname" . }}-openldap
  labels:
    app: {{ template "openldap.name" . }}-openldap
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.openldap.enabled }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.openldap.type }}
  {{- if (or (eq .Values.service.openldap.type "LoadBalancer") (eq .Values.service.openldap.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.openldap.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: container
      {{- if (and (eq .Values.service.openldap.type "NodePort") (not (empty .Values.service.openldap.nodePorts.http))) }}
      nodePort: {{ .Values.service.openldap.nodePorts.http }}
      {{- end }}
  selector:
    app: {{ template "openldap.name" . }}-openldap
    release: {{ .Release.Name }}
