{{- if (and .Values.persistence.enabled (eq .Values.persistence.existingClaim "")) }}
kind: persistentvolumeclaim
apiversion: v1
metadata:
  name: {{ template "gitlab.fullname" . }}-data
  labels:
    app: {{ template "gitlab.name" . }}-data
    chart: {{ .chart.name }}-{{ .chart.version }}
    release: {{ .release.name }}
    heritage: {{ .release.service }}
spec:
  accessmodes:
    - {{ .values.persistence.accessmode }}
  resources:
    requests:
      storage: {{ .values.persistence.size }}
{{- if .values.persistence.storageclass }}
{{- if (eq "-" .values.persistence.storageclass) }}
  storageclassname: ''
{{- else }}
  storageclassname: {{ .values.persistence.storageclass }}
{{- end }}
{{- end }}
---
kind: persistentvolumeclaim
apiversion: v1
metadata:
  name: {{ template "gitlab.fullname" . }}-etc
  labels:
    app: {{ template "gitlab.name" . }}-etc
    chart: {{ .chart.name }}-{{ .chart.version }}
    release: {{ .release.name }}
    heritage: {{ .release.service }}
spec:
  accessmodes:
    - {{ .values.persistence.accessmode }}
  resources:
    requests:
      storage: {{ .values.persistence.size }}
{{- if .values.persistence.storageclass }}
{{- if (eq "-" .values.persistence.storageclass) }}
  storageclassname: ''
{{- else }}
  storageclassname: {{ .values.persistence.storageclass }}
{{- end }}
{{- end }}
{{- end }}
