images:
  mongoExpress:
    repository: mongo-express
    tag: 0.49.0
    pullPolicy: IfNotPresent

config:
  customConfig: ''
  password: password
  pause: true
  prometheus: false
  terminationPolicy: Delete
  updateStrategy: RollingUpdate
  version: 4.1.13
  mongoExpress:
    enabled: true
    password: pass
    username: admin
  replicaSet:
    enabled: false
    replicas: 3
  shardTopology:
    configServerReplicas: 3
    enabled: false
    mongosReplicas: 2
    shards: 3

service:
  mongoExpress:
    type: NodePort
    externalTrafficPolicy: Cluster
    nodePorts:
      http: ''
  mongodb:
    type: ClusterIP
    externalTrafficPolicy: Cluster
    nodePorts:
      mongodb: ''

ingress:
  mongoExpress:
    certificate: ''
    enabled: false
    hostname: ''
    path: /
    tls: false
    issuer:
      name: letsencrypt-staging

issuer:
  name: letsencrypt-staging
  kind: ClusterIssuer

persistence:
  accessMode: ReadWriteOnce
  enabled: false
  existingClaim: ''
  size: 1Gi
  storageClass: ''
  velero:
    enabled: false
  stash:
    enabled: false
    keepLast: 30
    paused: false
    repository: stash-stash
    schedule: '0 0 * * *'
    restore:
      snapshot: ''

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
