apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.fullname" . }}-mongodb
  labels:
    app: {{ template "mongodb.name" . }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MONGODB_PASSWORD: {{ .Values.config.password | b64enc }}
  MONGODB_USER: {{ "mongodb" | b64enc }}
