{{- if .Values.config.mysql.internal }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dbtest.fullname" . }}-mysql
  labels:
    app: {{ template "dbtest.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  my-config.cnf: {{ .Values.config.mysql.customConfig | quote }}
{{- end }}
