{{- if .Values.config.phpmyadmin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  phpmyadmin_email: {{ .Values.config.phpmyadmin.email | quote }}
{{- end }}
