apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: {{ template "mysql.fullname" . }}-mysql
  labels:
    app: {{ template "mysql.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  version: {{ .Values.config.version | quote }}
  configSource:
    configMap:
      name: {{ template "mysql.fullname" . }}-mysql
  standbyMode: {{ .Values.config.standbyMode | quote }}
  {{- if .Values.config.prometheus }}
  monitor:
    agent: prometheus.io/builtin
  {{- end }}
  {{- if .Values.persistence.enabled }}
  storageType: Durable
  storage:
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
    storageClassName: ''
    {{- else }}
    storageClassName: {{ .Values.persistence.storageClass }}
    {{- end }}
    {{- end }}
    accessModes:
      - {{ .Values.persistence.accessMode }}
    resources:
      requests:
        storage: {{ .Values.persistence.size }}
  {{- else }}
  storageType: Ephemeral
  {{- end }}
  {{- if (not (empty .Values.config.backup.enabled)) }}
  backupSchedule:
    cronExpression: {{ .Values.config.backup.cron | quote }}
    storageSecretName: {{ template "mysql.fullname" . }}-mysql
    {{ .Values.config.backup.type }}:
      {{- if (or (eq "gcs" .Values.config.backup.type) (eq "s3" .Values.config.backup.type)) }}
      bucket: {{ .Values.config.backup.bucket | quote }}
      {{- end }}
      {{- if (eq "s3" .Values.config.backup.type) }}
      endpoint: {{ .Values.config.backup.endpoint | quote }}
      {{- end }}
      {{- if (eq "azure" .Values.config.backup.type) }}
      container: {{ .Values.config.backup.container | quote }}
      {{- end }}
      prefix: {{ .Values.config.backup.prefix | quote }}
  {{- end }}
  {{- if (not (empty .Values.config.restoreFromSnapshot)) }}
  init:
    snapshotSource:
      name: {{ .Values.config.restoreFromSnapshot | quote }}
      namespace: {{ .Release.Namespace }}
  {{- end }}
