apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.fullname" . }}-mysql
  labels:
    app: {{ template "mysql.name" . }}-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.config.password | b64enc }}
  username: {{ "mysql" | b64enc }}
