apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.config.baseUrl }}
  base_url: {{ .Values.config.baseUrl | quote }}
  {{- else }}
  {{- if .Values.ingress.enabled }}
  {{- $host := (index .Values.ingress.hosts.gitlab 0) }}
  {{- $protocol := "http" }}
  {{- if .Values.ingress.tls }}
  {{- $protocol := (printf "%ss" $protocol) }}
  {{- end }}
  base_url: {{ $protocol }}://{{ $host.name }}{{ $host.path }}
  {{- else }}
  base_url: http://{{ template "gitlab.fullname" . }}-gitlab
  {{- end }}
  {{- end }}
  {{- $postgres := .Values.config.postgres }}
  {{- if $postgres.internal }}
  postgres_host: {{ template "gitlab.fullname" . }}-postgres
  {{- else }}
  postgres_host: {{ $postgres.host | quote }}
  {{- end }}
  postgres_database: {{ $postgres.database | quote }}
  postgres_port: {{ $postgres.port | quote }}
  postgres_username: {{ $postgres.username | quote }}
  {{- $redis := .Values.config.redis }}
  {{- if $redis.internal }}
  redis_host: {{ template "gitlab.fullname" . }}-redis
  {{- else }}
  redis_host: {{ $redis.host | quote }}
  {{- end }}
  redis_port: {{ $redis.port | quote }}
  redis_username: {{ $redis.username | quote }}
  omnibus_config: ''
