apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gluu.fullname" . }}-gluu
  labels:
    app: {{ template "gluu.name" . }}-gluu
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
