apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailserver.fullname" . }}
  labels:
    app: {{ template "mailserver.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data: {}
